### ISSUE TITLE
Sprint 2 is Incomplete

### ISSUE THREAD

**Issue by jcjordyn130** [jcjordyn130/IntroToSEProjectFall2024#6]
Due: 9/25/2024
- [x] Use Case Diagrams - @bdb4 
- [x] UML Class Diagrams - @jcjordyn130 
- [x] UML Sequence Diagrams for Each User Story - @ScottReidCS 
- [x] UML State Diagrams and Activity Diagrams for Each User Story - @MadduxLofton 
- [x] Architectural Design Diagram for Web Application - @jcjordyn130 
- [x] Component-level Design Diagram Based on the Architecture - @bdb4

**Comment by bdb4** [comment]
I'll add more use cases for buyers and sellers and update the use case diagram with them.

**Comment by jcjordyn130** [comment]
How's the progress on this looking?

**Comment by bdb4** [comment]
Maddux is still working on it I think.

**Comment by MadduxLofton** [comment]
I finished it last night I just forgot to hit the button.
